# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    API_KEY: '%env(API_KEY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    serializer.name_converter.camel_case_to_snake_case:
        class: Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter

    Symfony\Component\Serializer\Normalizer\ObjectNormalizer:
        arguments:
            $nameConverter: '@serializer.name_converter.snake_case_to_camel_case'
            $classMetadataFactory: null
            $propertyAccessor: '@property_accessor'
            $propertyTypeExtractor: null

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        public: true
        
    App\EventListener\CheckApiKeyListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
